'\" t
.\" UCSD p-System Operating System
.\" Copyright (C) 2010 Peter Miller
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions are met:
.\"
.\"   * Redistributions of source code must retain the above copyright notice,
.\"     this list of conditions and the following disclaimer.
.\"   * Redistributions in binary form must reproduce the above copyright
.\"     notice, this list of conditions and the following disclaimer in the
.\"     documentation and/or other materials provided with the distribution.
.\"   * Neither the name of the ucsd-psystem-os project nor the names of its
.\"     contributors may be used to endorse or promote products derived from
.\"     this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
.\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.ds n) ucsdpsys_os_license_bsd
.TH \*(n) 1 ucsd-psystem-os "Reference Manual"
.SH NAME
ucsdpsys_os_license_bsd \- UCSD p-System thingummy
.XX "ucsdpsys_os_license_bsd(1)" "UCSD p-System thingummy"
.SH SYNOPSIS
\fB\*(n)\fP [ \fIoption\fP... ] \fIfilename\P...
.br
\fB\*(n) \-V\fP
.SH DESCRIPTION
The \fI\*(n)\fP program is used to
.br
.ne 1i
.SH OPTIONS
The following options are understood:
.TP 8n
\fB\-V\fP
.br
Print the version of the \fI\*(n)\fP program being executed.
.PP
All other options will produce a diagnostic error.
.so z_exit.so
.so z_copyright.so
