'\" t
.\" UCSD p-System Operating System
.\" Copyright (C) 2006, 2009, 2010 Peter Miller
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions are met:
.\"
.\"   * Redistributions of source code must retain the above copyright notice,
.\"     this list of conditions and the following disclaimer.
.\"   * Redistributions in binary form must reproduce the above copyright
.\"     notice, this list of conditions and the following disclaimer in the
.\"     documentation and/or other materials provided with the distribution.
.\"   * Neither the name of the ucsd-psystem-os project nor the names of its
.\"     contributors may be used to endorse or promote products derived from
.\"     this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
.\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.TH "Read Me" ucsd-psystem-os ucsd-psystem-os "Reference Manual"
.so version.so
.hy 0
.ad l
.SH NAME
ucsd-psystem-os \- UCSD p-System file system
.XX "" "The README file"
.SH DESCRIPTION
The \f[I]ucsd-psystem-os\fP package is composed of several programs which
collectively form the UCSD p-System operating system.
.br
.ne 1i
.SH ARCHIVE SITE
The latest version of
.I ucsd-psystem-os
is available on the Web from:
.RS 4m
.TS
tab(;);
l l s
l l l.
URL:;http://miller.emu.id.au/pmiller/ucsd-psystem-os/
File:;index.html;# the ucsd-psystem-os home page
File:;ucsd-psystem-os-\*(v).tar.gz;# the complete source
.TE
.RE
.br
.ne 1i
.SH BUILDING ucsd-psystem-os
Full instructions for building \f[I]ucsd-psystem-os\fP may be found on
the web at
http://miller.emu.id.au/pmiller/ucsd-psystem-os/building.html
.SH LICENSE
See the LICENSE and LICENSE-UCSD files included in the source tarball.
.SH MAINTAINER
.TS
tab(;);
l r l.
Peter Miller;E-Mail:;pmiller@opensource.org.au
\f(CW/\e/\e*\fP;WWW:;http://miller.emu.id.au/pmiller/
.TE
